### ISSUE TITLE
Cocoapods dependency error between SearchSDK and MapboxMaps v10

### ISSUE THREAD

**Issue by bismark-jp** [mapbox/search-ios#6]
I have tried to update MapSDK to v10, but had a dependency error between this search SDK. Please take a look.

```
  ...
  pod 'MapboxMaps', '10.1.0'
  pod 'MapboxSearchUI', ">= 1.0.0-beta.15", "< 2.0"
  ...
```

```
$ pod install

[!] CocoaPods could not find compatible versions for pod "MapboxCommon":
  In snapshot (Podfile.lock):
    MapboxCommon (= 20.1.0, ~> 20.1)

  In Podfile:
    MapboxSearchUI (< 2.0, >= 1.0.0-beta.15) was resolved to 1.0.0-beta.15, which depends on
      MapboxSearch (< 2.0, >= 1.0.0-beta.15) was resolved to 1.0.0-beta.15, which depends on
        MapboxCommon (~> 20.0.0)

Specs satisfying the `MapboxCommon (= 20.1.0, ~> 20.1), MapboxCommon (~> 20.0.0)` dependency were found, but they required a higher minimum deployment target.
```

**Comment by don1ck** [comment]
Hello @bismark-jp , sorry for delay.
You can now use `1.0.0-beta.16` for Maps` v10.1.0`

```
  ...
  pod 'MapboxMaps', '10.1.0'
  pod 'MapboxSearchUI', ">= 1.0.0-beta.16", "< 2.0"
  ...
```

**Comment by bismark-jp** [comment]
Thanks, I will try again.

**Comment by jvanakker** [comment]
This issue can be re-opened. Same problem is happening now, when installing with with the following, as is described in the current documentation:
`pod 'MapboxSearchUI', ">= 1.0.0-beta.18", "< 2.0"`
Problem:
"CocoaPods could not find compatible versions for pod "MapboxCommon"
For me it works by temporarily reverting to beta.16.
