### ISSUE TITLE
Hide categories/favorites altogether

### ISSUE THREAD

**Issue by linearray** [mapbox/search-ios#9]
In one place in my app I need to hide the categories button (and optionally the favorites button too) in the Search Panel:

<img width="554" alt="Screen Shot 2021-11-29 at 14 17 26" src="https://user-images.githubusercontent.com/1019302/143877821-b98d4802-275a-443d-839a-e7710562dd5c.png">

I did not find a way to do this right now. Setting `hideCategorySlots` to `true` and `categoryDataProvider: ConstantCategoryDataProvider(slots: [], list: [])` does not do the trick.

Is this behavior achievable? A very acceptable and even desirable alternative for my use case would be another option in `MapboxPanelController.State` for "show only the search field and nothing else", like so:

<img width="554" alt="Screen Shot 2021-11-29 at 15 05 51" src="https://user-images.githubusercontent.com/1019302/143882365-e5b128a5-6de1-4608-8b5d-97cabedee95d.png">

**Comment by don1ck** [comment]
Hi @linearray,
You are right, unfortunately `hideCategorySlots` hides only "hot" categories:

<img width="331" alt="Screenshot 2021-12-02 at 12 38 13" src="https://user-images.githubusercontent.com/1050454/144400375-7bfba65c-174f-4436-b1e4-ce3e5de76a93.png">

Currently there is no way to show "search bar only".  But it seems like a nice option to have, we will consider it. 
Thank you for report.

**Comment by jvanakker** [comment]
> Hi @linearray, You are right, unfortunately `hideCategorySlots` hides only "hot" categories:
> 
> <img alt="Screenshot 2021-12-02 at 12 38 13" width="331" src="https://user-images.githubusercontent.com/1050454/144400375-7bfba65c-174f-4436-b1e4-ce3e5de76a93.png">
> 
> Currently there is no way to show "search bar only". But it seems like a nice option to have, we will consider it. Thank you for report.

I agree, also for my app it would be a must to have this option. Also the option to just (and only) show "Favorites".
I've done the same workaround for now, having categoryList and categorySlots empty. But it still shows the bar with both "Categories" and "Favorites". The "Categories" list is now empty, but it's not a clean solution.

**Comment by don1ck** [comment]
Moved to https://github.com/mapbox/search-ios/issues/28 and https://github.com/mapbox/search-ios/issues/27
